version: "3"
services:
    proxy:
        build:
            proxy/
        ports:
            - "80:80"
        links:
            - front
            - api
        container_name:
            proxy
    front:
        build:
            front/
        container_name:
            front
    api:
        build:
            api/
        container_name:
            api

